### PR TITLE
bug/minor: MySql: fix healthcheck crash

### LINKED ISSUE #38: Issue with running update when MySQL has no healthcheck
If the mysql container has no healthcheck values (older YAML file), the update-db-schema function will fail to parse docker inspect and this loop will become infinite: https://github.com/elabftw/elabctl/blob/dad670c9e7dd3292b7526161c437f2224c148d99/elabctl.sh#L561

The inspect command must first check if healthcheck is available in the inspect output, if not, wait for 20 seconds.

### PR DESCRIPTION
**Pull request by MoustaphaCamara**
Fix #38 
update-db-schema fails to parse docker when mysql container has no healthcheck values.

- check if healthcheck is available before continuing. If not detectable, wait 20 seconds and retry.

- no healthcheck : 
no-healthcheck

- waiting for mysql container :
waiting

- healthy
Capture d’écran du 2024-12-12 11-31-56

### CODE REVIEW

File: elabctl.sh [hunk 1]
```diff
@@ -558,7 +558,22 @@ function update-db-schema
     # wait for mysql container to start, but only if there is one
     if [ "$(docker ps | grep ${ELAB_MYSQL_CONTAINER_NAME})" ]; then
         echo -n "Waiting for the MySQL container to be ready before running update..."
-        while [ "$(docker inspect -f {{.State.Health.Status}} ${ELAB_MYSQL_CONTAINER_NAME})" != "healthy" ]; do echo -n .; sleep 2; done; echo
+        while true; do
+            # check if healthcheck is available or else will crash (e.g with older versions of elabFTW config files)
+            health_status=$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}no-healthcheck{{end}}' ${ELAB_MYSQL_CONTAINER_NAME})
+            if [ "$health_status" == "healthy" ]; then
+                echo
```
Comment (MoustaphaCamara) [inline elabctl.sh:565]: why
```suggestion
                echo
```

**Review by NicolasCARPi — CHANGES_REQUESTED** [review]
please run through shellcheck and add double quotes where needed

**Comment by MoustaphaCamara** [comment]
> please run through shellcheck and add double quotes where needed

I fixed for this issue, I'll make another PR to address other shellcheck warnings for this file, so i can test it thoroughly before comitting :)

**Review by NicolasCARPi — APPROVED** [review]
Thanks!

**Comment by alexander-haller** [comment]
Do you no longer increment versions when committing to master?

**Comment by NicolasCARPi** [comment]
image
